const now = new Date();

export const MOCK_CATEGORIES = [
  { id: "1", name: "Lubumbashi", slug: "lubumbashi", order: 1, description: null, color: null, parentId: null, createdAt: now, updatedAt: now },
  { id: "2", name: "Haut-Katanga", slug: "haut-katanga", order: 2, description: null, color: null, parentId: null, createdAt: now, updatedAt: now },
  { id: "3", name: "RDC", slug: "rdc", order: 3, description: null, color: null, parentId: null, createdAt: now, updatedAt: now },
  { id: "4", name: "Politique", slug: "politique", order: 4, description: null, color: null, parentId: null, createdAt: now, updatedAt: now },
  { id: "5", name: "Économie", slug: "economie", order: 5, description: null, color: null, parentId: null, createdAt: now, updatedAt: now },
  { id: "6", name: "Sport", slug: "sport", order: 6, description: null, color: null, parentId: null, createdAt: now, updatedAt: now },
  { id: "7", name: "Afrique", slug: "afrique", order: 7, description: null, color: null, parentId: null, createdAt: now, updatedAt: now },
  { id: "8", name: "International", slug: "international", order: 8, description: null, color: null, parentId: null, createdAt: now, updatedAt: now },
  { id: "9", name: "Technologie", slug: "tech", order: 9, description: null, color: null, parentId: null, createdAt: now, updatedAt: now },
  { id: "10", name: "Société", slug: "societe", order: 10, description: null, color: null, parentId: null, createdAt: now, updatedAt: now },
];

const cat = (slug: string) => MOCK_CATEGORIES.find((c) => c.slug === slug)!;

export const MOCK_ARTICLES = [
  {
    id: "a1",
    title: "Lubumbashi : le gouverneur du Haut-Katanga annonce de nouveaux investissements miniers",
    slug: "lubumbashi-investissements-miniers-haut-katanga",
    subtitle: "Un plan de développement économique de 500 millions de dollars présenté ce mardi",
    excerpt: "Le gouverneur du Haut-Katanga a dévoilé un ambitieux plan d'investissement visant à moderniser l'infrastructure minière de la province.",
    content: "<p>En marge d'une conférence de presse tenue à Lubumbashi, le gouverneur a présenté un plan de développement économique d'une envergure inédite.</p>",
    contentType: "FAITS" as const,
    status: "PUBLIE" as const,
    featuredImage: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=1200&h=675&fit=crop",
    featuredImageAlt: "Vue aérienne de Lubumbashi",
    featuredImageCaption: null,
    gallery: null,
    keyPoints: ["Plan de 500 M$", "5 000 emplois prévus"],
    isBreaking: true,
    isFeatured: true,
    isSponsored: false,
    isFactCheck: false,
    factCheckVerdict: null,
    geoZone: "Lubumbashi",
    africaRegion: null,
    intlRegion: null,
    viewCount: 4821,
    shareCount: 0,
    readTimeMinutes: 4,
    publishedAt: now,
    scheduledAt: null,
    createdAt: now,
    updatedAt: now,
    categoryId: "1",
    authorId: null,
    userId: null,
    sourceId: null,
    category: cat("lubumbashi"),
    author: { id: "auth1", name: "Rédaction LUSHIPOST", slug: "redaction", bio: null, avatar: null, email: null, twitter: null, linkedin: null, createdAt: now, updatedAt: now },
    source: { id: "s1", name: "LUSHIPOST", url: null, logo: null, createdAt: now },
    tags: [],
  },
  {
    id: "a2",
    title: "RDC : le président reçoit les ambassadeurs du G7 à Kinshasa",
    slug: "rdc-president-ambassadeurs-g7-kinshasa",
    subtitle: "Discussions sur la coopération économique et la sécurité régionale",
    excerpt: "Le chef de l'État congolais a reçu une délégation d'ambassadeurs du G7.",
    content: "<p>Une rencontre de haut niveau s'est tenue ce lundi au Palais de la Nation.</p>",
    contentType: "FAITS" as const,
    status: "PUBLIE" as const,
    featuredImage: "https://images.unsplash.com/photo-1529107386315-e1a2ecb4819d?w=800&h=500&fit=crop",
    featuredImageAlt: null,
    featuredImageCaption: null,
    gallery: null,
    keyPoints: null,
    isBreaking: false,
    isFeatured: false,
    isSponsored: false,
    isFactCheck: false,
    factCheckVerdict: null,
    geoZone: null,
    africaRegion: null,
    intlRegion: null,
    viewCount: 3210,
    shareCount: 0,
    readTimeMinutes: 3,
    publishedAt: new Date(now.getTime() - 3600000),
    scheduledAt: null,
    createdAt: now,
    updatedAt: now,
    categoryId: "4",
    authorId: null,
    userId: null,
    sourceId: null,
    category: cat("politique"),
    author: null,
    source: null,
    tags: [],
  },
  {
    id: "a3",
    title: "Sport : le TP Mazembe prépare la saison 2026-2027",
    slug: "sport-tp-mazembe-saison-2026",
    subtitle: "Le club lubumbashiens vise la Ligue des Champions CAF",
    excerpt: "Le Tout Puissant Mazembe entame sa préparation pour la nouvelle saison.",
    content: "<p>Le TP Mazembe a officiellement lancé sa préparation.</p>",
    contentType: "FAITS" as const,
    status: "PUBLIE" as const,
    featuredImage: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&h=500&fit=crop",
    featuredImageAlt: null,
    featuredImageCaption: null,
    gallery: null,
    keyPoints: null,
    isBreaking: false,
    isFeatured: false,
    isSponsored: false,
    isFactCheck: false,
    factCheckVerdict: null,
    geoZone: "Lubumbashi",
    africaRegion: null,
    intlRegion: null,
    viewCount: 3890,
    shareCount: 0,
    readTimeMinutes: 3,
    publishedAt: new Date(now.getTime() - 7200000),
    scheduledAt: null,
    createdAt: now,
    updatedAt: now,
    categoryId: "6",
    authorId: null,
    userId: null,
    sourceId: null,
    category: cat("sport"),
    author: null,
    source: null,
    tags: [],
  },
];

export const MOCK_BREAKING = [
  {
    id: "b1",
    title: "Lubumbashi : le gouverneur annonce un plan d'investissement de 500 M$",
    url: null,
    articleId: "a1",
    isActive: true,
    order: 0,
    createdAt: now,
    expiresAt: null,
    article: MOCK_ARTICLES[0],
  },
];

export const MOCK_VIDEOS = [
  {
    id: "v1",
    title: "Reportage : une journée dans les mines du Haut-Katanga",
    slug: "reportage-mines-haut-katanga",
    description: "Immersion au cœur de l'industrie minière congolaise.",
    thumbnail: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=640&h=360&fit=crop",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    platform: "youtube",
    duration: 720,
    isVertical: false,
    viewCount: 1200,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
];

export const MOCK_SOCIAL = [
  { platform: "facebook", url: "#" },
  { platform: "instagram", url: "#" },
  { platform: "x", url: "#" },
  { platform: "linkedin", url: "#" },
];
