"use client";

import { useEffect, useState } from "react";
import { Heart, MessageCircle } from "lucide-react";
import { useSession } from "next-auth/react";

type Comment = { id: string; content: string; author: string };

export function ArticleEngagement({ articleId }: { articleId: string }) {
  const { status } = useSession();
  const [liked, setLiked] = useState(false); const [likeCount, setLikeCount] = useState(0); const [comments, setComments] = useState<Comment[]>([]);
  const [content, setContent] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [loadingLike, setLoadingLike] = useState(false); const [loadingComment, setLoadingComment] = useState(false);
  useEffect(() => { fetch(`/api/articles/${articleId}/engagement`).then(async (response) => response.ok ? response.json() : null).then((data) => { if (data) { setLiked(data.liked); setLikeCount(data.likeCount); setComments(data.comments); } }).catch(() => setError("Impossible de charger les réactions.")); }, [articleId]);
  const toggleLike = async () => { setError(""); setMessage(""); if (status !== "authenticated") return setError("Connectez-vous pour aimer cet article."); setLoadingLike(true); try { const response = await fetch(`/api/articles/${articleId}/engagement`, { method: "PUT" }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Impossible de mettre à jour le like."); setLiked(data.liked); setLikeCount(data.likeCount); } catch (caught) { setError(caught instanceof Error ? caught.message : "Impossible de mettre à jour le like."); } finally { setLoadingLike(false); } };
  const submitComment = async (event: React.FormEvent) => { event.preventDefault(); setError(""); setMessage(""); if (status !== "authenticated") return setError("Connectez-vous pour commenter."); setLoadingComment(true); try { const response = await fetch(`/api/articles/${articleId}/engagement`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ content }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Impossible d’envoyer le commentaire."); setContent(""); setMessage(data.message); } catch (caught) { setError(caught instanceof Error ? caught.message : "Impossible d’envoyer le commentaire."); } finally { setLoadingComment(false); } };
  return <section className="mt-8 border-t border-gray-200 pt-6" aria-label="Réactions et commentaires"><button type="button" onClick={toggleLike} disabled={loadingLike} aria-pressed={liked} className={`inline-flex items-center gap-2 rounded-sm border px-4 py-2 text-sm font-semibold ${liked ? "border-red-600 bg-red-50 text-red-700" : "border-gray-200 hover:border-red-400"}`}><Heart className={`h-4 w-4 ${liked ? "fill-current" : ""}`} /> {likeCount} j’aime{likeCount > 1 ? "s" : ""}</button><div className="mt-8"><h2 className="flex items-center gap-2 text-xl font-bold"><MessageCircle className="h-5 w-5" /> Commentaires</h2><form onSubmit={submitComment} className="mt-4 space-y-3"><textarea value={content} onChange={(event) => setContent(event.target.value)} required minLength={3} maxLength={2000} placeholder="Partagez votre réaction…" className="lp-form-input min-h-28" /><button disabled={loadingComment} className="lp-btn-primary">{loadingComment ? "Envoi…" : "Envoyer le commentaire"}</button></form>{message && <p className="mt-3 text-sm text-green-700" role="status">{message}</p>}{error && <p className="mt-3 text-sm text-red-700" role="alert">{error}</p>}<div className="mt-6 space-y-4">{comments.map((comment) => <article key={comment.id} className="border-l-2 border-lp-accent bg-lp-light p-4"><p className="font-semibold">{comment.author}</p><p className="mt-2 whitespace-pre-wrap text-sm">{comment.content}</p></article>)}{comments.length === 0 && <p className="text-sm text-lp-gray">Aucun commentaire approuvé pour le moment.</p>}</div></div></section>;
}
